Repository SejongPeer/SejongPeerFront, pull requests merged in 2024-08, with the labels that each got.

#372 feat : [24] 게시글 작성 데탑버전 & 게시글 작성 후 페이지 이동
  src/components/button/submitButton/SubmitBtn.module.css
  src/components/studyPostWrite/ImageUpload.module.css
  src/components/studyPostWrite/PostHeader.js
  src/components/studyPostWrite/PostHeader.module.css
  src/components/studyPostWrite/PostInput.module.css
  src/components/studyPostWrite/StudyRequirement.js
  src/components/studyPostWrite/StudyRequirement.module.css
  src/components/studyPostWrite/studyRequirement/RecruitDate.js
  src/components/studyPostWrite/studyRequirement/StudyLink.module.css
  src/components/studyPostWrite/studyRequirement/Tag.js
  src/pages/study/studyPostWrite/StudyPostWrite.js
  src/pages/study/studyPostWrite/StudyPostWrite.module.css
Labels: feature

#374 feat : [25] 카테고리(교내) 선택
  public/TimeTable.xlsx
  src/components/modal/BottomModal.js
  src/components/studyPostWrite/studyRequirement/Category.js
  src/pages/study/studyPostWrite/StudyPostWrite.js
  src/pages/study/studyPostWrite/studyPostField/StudyPostField.js
  src/pages/study/studyPostWrite/studyPostField/StudyPostField.module.css
  src/pages/study/studyPostWrite/usePostStore.js
  src/pages/study/timeTable/getTimeTable.js
  src/pages/study/timeTable/useTimeTableStore.js
Labels: feature

#376 feat: [26] 스크랩 수 및 교외 리스트 구현
  package-lock.json
  package.json
  public/2024-2강의시간표(한국어)_20240726.xlsx
  src/components/modal/BottomModal.module.css
  src/pages/main/mainPage/MainPage.js
  src/pages/main/mainPage/MainPage.module.css
  src/pages/study/studyList/StudyList.js
  src/pages/study/studyList/StudyListPost.js
  src/pages/study/studyList/api.js
Labels: feature

#380 feat : [28] 게시글 작성 -> alert & 작성한 스터디 지원자 조회 css & 수락 거절 통신
  src/components/studyMyPost/api/applicantSelection.js
  src/components/studyMyPost/api/earlyClose.js
  src/components/studyMyPost/api/fetchMyPost.js
  src/components/studyMyPost/studyMyPost.js
  src/pages/myPage/myPost/myPost.js
  src/pages/study/studyPostWrite/StudyPostWrite.js
Labels: feature

#382 feat: 게시글 사진 렌더링 등
  src/components/modal/BottomModal.js
  src/components/studyPostWrite/StudyRequirement.module.css
  src/components/studyPostWrite/studyRequirement/DateFrequency.js
  src/components/studyPostWrite/studyRequirement/MeetingWay.js
  src/pages/myPage/mypage/MyPage.js
  src/pages/study/studyPostDetail/StudyPostDetail.js
  src/pages/study/studyPostDetail/api.js
  src/pages/study/studyPostWrite/ConfirmModal.js
  src/pages/study/studyPostWrite/ConfirmModal.module.css
  src/pages/study/studyPostWrite/StudyPostWrite.js
  src/pages/study/studyPostWrite/confirmModal/ConfirmModal.js
  src/pages/study/studyPostWrite/confirmModal/ConfirmModal.module.css
Labels: feature

#384 feat: [30] 내가 지원한 스터디 조회
  jsconfig.json
  package-lock.json
  package.json
  src/App.js
  src/pages/login/signIn/SignIn.js
  src/pages/login/signUp/SignUp.js
  src/pages/login/signUp/auth/Auth.js
  src/pages/main/mainPage/MainPage.js
  src/pages/main/mainPage/api.js
  src/pages/myPage/modify/Modify.js
  src/pages/myPage/mypage/AppliedStudy.js
  src/pages/myPage/mypage/MyPage.js
  src/pages/myPage/mypage/MyPage.module.css
  src/pages/myPage/mypage/api.js
  src/pages/study/studyList/StudyListPost.js
  src/pages/study/studyList/api.js
  src/pages/study/studyPostDetail/StudyPostDetail.js
  src/pages/study/studyPostDetail/api.js
Labels: feature

#398 feat: [37] 지원한 스터디 디자인 수정
  src/pages/myPage/mypage/AppliedStudy.js
  src/pages/study/studyPostDetail/StudyPostDetail.js
Labels: feature, refactor

#406 feat: 이미지 확대 보기, 이미지 용량 에러처리, 통신 작업중
  public/index.html
  src/components/modal/Modal.js
  src/components/modal/Modal.module.css
  src/components/studyPostWrite/ImageUpload.js
  src/pages/myPage/mypage/MyPage.js
  src/pages/myPage/mypage/api.js
  src/pages/study/studyList/Filter_Field.js
  src/pages/study/studyList/Filter_Field.module.css
  src/pages/study/studyList/Filter_Field2.js
  src/pages/study/studyList/Filter_Member.js
  src/pages/study/studyList/StudyList.js
  src/pages/study/studyList/api.js
  src/pages/study/studyList/useFilterStore.js
  src/pages/study/studyList/useTimetableStore.js
  src/pages/study/studyPostDetail/StudyPostDetail.js
  src/pages/study/studyPostWrite/StudyPostWrite.js
Labels: feature

#408 refactor: [42] MainPage refactor
  src/assets/image/external.png
  src/components/header/Header.module.css
  src/components/studyMyPost/studyMyPost.js
  src/components/studyPostWrite/studyRequirement/Category.js
  src/pages/buddy/accept/BuddyAccept.js
  src/pages/buddy/matching/js/Buddy_Final.js
  src/pages/buddy/waiting/BuddyWaiting.js
  src/pages/festival/animalApply2/AnimalApply2.js
  src/pages/festival/animalApply5/AnimalApply5.js
  src/pages/festival/animalCheck/AnimalCheck.js
  src/pages/festival/animalMatchResult/AnimalMatchInfo.js
  src/pages/festival/animalResult/AnimalResult.js
  src/pages/honbob/matching/js/Honbob_Matching.js
  src/pages/honbob/waiting/HonbobWaiting.js
  src/pages/login/find/findId/FindId.js
  src/pages/login/find/resetPwd/ResetPwd.js
  src/pages/login/signUp/Agree.js
  src/pages/login/signUp/EmailBox.js
  src/pages/login/signUp/IDCheckBox.js
  src/pages/login/signUp/NickNameBox.js
  src/pages/login/signUp/SignUp.js
  src/pages/main/mainPage/MainPage.js
  src/pages/main/mainPage/api.js
  src/pages/myPage/modify/Modify.js
  src/pages/study/studyList/api.js
  src/pages/study/studyPostDetail/api.js
  src/pages/study/studyPostWrite/StudyPostWrite.js
Labels: refactor

#410 refactor: [43] Header, 페이지 디자인 Refactor
  src/App.js
  src/assets/image/backArrow.png
  src/assets/image/buddyImg3.png
  src/assets/image/buddyImg4.png
  src/assets/image/buddyImg5.png
  src/assets/image/buddyStart2.png
  src/assets/image/peerLogo.png
  src/assets/image/user.png
  src/components/header/Back.js
  src/components/header/Header.module.css
  src/components/headerRefactor/MainHeader.js
  src/components/headerRefactor/SubHeader.js
  src/components/studyMyPost/navBar.js
  src/components/studyPopup/Popup.js
  src/pages/buddy/info/BuddyStart.module.css
  src/pages/buddy/info/BuddyStart1.js
  src/pages/buddy/info/BuddyStart2.js
  src/pages/buddy/matching/css/B_Btn3.module.css
  src/pages/buddy/matching/css/B_Container.module.css
  src/pages/buddy/matching/js/B_BuddyType.js
  src/pages/buddy/matching/js/B_Grade.js
  src/pages/buddy/matching/js/Buddy_Matching.js
  src/pages/buddy/progressBar/ProgressBar.js
  src/pages/buddy/progressBar/ProgressBar.module.css
  src/pages/buddy/waiting/BuddyWaiting.js
  src/pages/buddy/waiting/BuddyWaiting.module.css
  src/pages/honbob/info/HonbobStart.module.css
  src/pages/honbob/info/HonbobStart1.js
  src/pages/login/find/findId/FindId.js
  src/pages/login/signIn/SignIn.js
  src/pages/login/signIn/SignIn.module.css
  src/pages/login/signUp/Agree.js
  src/pages/login/signUp/IDCheckBox.js
  src/pages/login/signUp/SignUp.js
  src/pages/login/signUp/SignUp.module.css
  src/pages/login/signUp/auth/Auth.js
  src/pages/login/signUp/auth/Auth.module.css
  src/pages/main/mainPage/MainPage.js
  src/pages/main/mainPage/MainPage.module.css
  src/pages/main/mainPage/api.js
  src/pages/myPage/modify/Modify.js
  src/pages/myPage/modify/Modify.module.css
  src/pages/myPage/myPost/myPost.js
  src/pages/myPage/mypage/AppliedStudy.js
  src/pages/myPage/mypage/MyPage.js
  src/pages/myPage/mypage/MyPage.module.css
  src/pages/myPage/mypage/MyPageScrapList.js
  src/pages/myPage/mypage/debug.log
  src/pages/study/studyList/StudyList.js
  src/pages/study/studyPostDetail/StudyPostDetail.js
Labels: feature, refactor

#412 feat: [44] 게시글 필터링 기능 완료 및 리스트 필터 모달 디자인 수정
  src/components/header/Back.js
  src/components/headerRefactor/SubHeader.js
  src/pages/study/studyList/Filter_Field.js
  src/pages/study/studyList/Filter_Field.module.css
  src/pages/study/studyList/Filter_Field2.js
  src/pages/study/studyList/Filter_Member.js
  src/pages/study/studyList/Filter_Member.module.css
  src/pages/study/studyList/Filter_now.js
  src/pages/study/studyList/Filter_now.module.css
  src/pages/study/studyList/StudyList.js
  src/pages/study/studyList/StudyListPost.js
  src/pages/study/studyList/api.js
  src/pages/study/studyPostDetail/StudyPostDetail.js
  src/pages/study/studyPostWrite/StudyPostWrite.js
Labels: feature

#414 feat : [45] 검색창 placeholder수정 , 수락/거절 이후 바로 바뀌게
  src/components/headerRefactor/SubHeader.js
  src/components/modal/BottomModal.module.css
  src/components/studyMyPost/navBar.js
  src/components/studyMyPost/studyMyPost.js
  src/components/studyPostWrite/studyRequirement/StudyLink.js
  src/pages/study/studyPostWrite/StudyPostWrite.js
  src/pages/study/studyPostWrite/StudyPostWrite.module.css
  src/pages/study/studyPostWrite/studyPostField/StudyPostExternalField.js
  src/pages/study/studyPostWrite/studyPostField/StudyPostField.js
  src/pages/study/studyPostWrite/studyPostField/StudyPostField.module.css
  src/pages/study/timeTable/useTimeTableStore.js
Labels: feature

#417 refactor: [51] 혼밥탈출 return
  src/assets/image/ChineseFood.png
  src/assets/image/JapaneseFood.png
  src/assets/image/KoreanFood.png
  src/assets/image/buddyUse.png
  src/assets/image/honbobStartLogo.png
  src/assets/image/honbobUse.png
  src/assets/image/honbobWaitingLogo.png
  src/assets/image/peerUse.png
  src/assets/image/westernFood.png
  src/pages/honbob/info/HonbobStart1.js
  src/pages/honbob/matching/css/H_Container.module.css
  src/pages/honbob/matching/css/H_Menu.module.css
  src/pages/honbob/matching/css/Honbob_Matching.module.css
  src/pages/honbob/matching/js/H_Gender.js
  src/pages/honbob/matching/js/H_InformCheck.js
  src/pages/honbob/matching/js/H_Menu.js
  src/pages/honbob/matching/js/Honbob_Matching.js
  src/pages/honbob/progressBar/ProgressBar_Honbob.js
  src/pages/honbob/progressBar/ProgressBar_Honbob.module.css
  src/pages/honbob/waiting/HonbobWaiting.js
  src/pages/honbob/waiting/HonbobWaiting.module.css
  src/pages/main/mainPage/MainPage.js
Labels: refactor

#419 refactor: [52] 스터디 지원 버그 수정
  src/pages/study/studyPostDetail/StudyPostDetail.js
Labels: refactor

#424 feat: [50] Google Analytics 설정
  public/index.html
  src/pages/study/studyPostDetail/StudyPostDetail.js
Labels: feature

#426 feat : [46] 거절 안됨 오류 / 인원수 잘못뜨는 오류 / 검색 필터링 기능 / 내가 쓴 게시글 지원자 리스트 예외처리
  src/components/studyMyPost/studyMyPost.js
  src/pages/study/studyList/Filter_Field.js
  src/pages/study/studyPostWrite/StudyPostWrite.js
  src/pages/study/studyPostWrite/studyPostField/StudyPostField.js
Labels: bug, feature
